### ISSUE TITLE
Please add support for List<T>?

### ISSUE THREAD

**Issue by zhengying** [garettbass/UnityExtensions.ArrayDrawer#8]
"List<T>" is used more common than "System.Array", can you add support for List<T>

**Comment by zhengying** [comment]
Sorry!  List is already supported.

**Comment by garettbass** [comment]
This library builds upon Unity’s SerializedProperty API, which treats System.Array and List <T> the same.  As a result, ArrayDrawer-based GUI works with all arrays and lists.

See this example: https://github.com/garettbass/UnityExtensions.ArrayDrawer/blob/master/ArrayDrawerExamples/SampleAsset.cs
