### ISSUE TITLE
Wrong ordering on drag/drop

### ISSUE THREAD

**Issue by belzecue** [garettbass/UnityExtensions.ArrayDrawer#9]
https://imgur.com/ybzdGWD

Not sure what's happening here with the out of sequence ordering...

**Comment by garettbass** [comment]
I recall fixing this bug in a fork of the project.  I believe the error is in the commit titled “new features for ReorderableLists“, in the changes to ReorderableListOfValues.cs, possibly around the methods OnSelectCallback() and OnReorderCallback(), maybe something wrong with my assumptions about the drag or drop index.

**Comment by garettbass** [comment]
If you are git-savvy, you may try syncing to just before that commit to see if the problem goes away.

**Comment by belzecue** [comment]
Thanks for looking into it.

I rolled back to 158770e11d7c0698ea941fcc2e5324128ebba9b5 (behind “new features for ReorderableLists“) and the ordering works as expected.

https://imgur.com/tY6PiT3

**Comment by Extrawurst** [comment]
How can this be fixed?

**Comment by garettbass** [comment]
Hello, I have pushed a fix for this issue.

**Comment by Extrawurst** [comment]
Thank you @garettbass so much! 👍
